import type { Metadata } from 'next';

import './globals.css';

import AppProviders from '@/components/AppProviders';
import Header from '@/components/Header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <AppProviders>
          <div className="min-h-screen bg-zinc-50 font-sans dark:bg-gray-950">
            <Header />
            {children}
          </div>
        </AppProviders>
      </body>
    </html>
  );
}
