const COINGECKO_ID_MAP: Record<string, string> = {
  ETH: 'ethereum',
  MATIC: 'polygon',
  BNB: 'binancecoin',
  AVAX: 'avalanche-2',
  OP: 'optimism',
  ARB: 'arbitrum',
  FTM: 'fantom',
  GNO: 'gnosis',
  ZK: 'zksync',
  XDAI: 'xdai',
  USDC: 'usd-coin',
  USDT: 'tether',
  DAI: 'dai',
  WBTC: 'wrapped-bitcoin',
  WETH: 'weth',
  LINK: 'chainlink',
  UNI: 'uniswap',
  POL: 'polygon-ecosystem-token',
  AAVE: 'aave',
  MKR: 'maker',
  LDO: 'lido-dao',
  BASE: 'base',
};
export default COINGECKO_ID_MAP;
